### ISSUE TITLE
New issue playing timed movie

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#15] opened 2022-07-16 15:30 UTC
Hi Heckie, I'm back with an issue I'm finding when using Timers for launching a Disney+ movie

I'm using an addon from Slyguy library (not the official Kodi library, unfortunately) for playing Disneyplus movies (I have a regular account on this platform).
When the time arrives for starting the player, I get an error from Timers and nothing works anymore, even for other timers set on later time.
See attached the log (look at 21:40)
Thanks for watching on this, I'm stuck on it with streaming movies in a Milan hospital
Thanks
Ciao
Fabio
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/9126108/kodi.log)

**Comment by bttfba** [comment] 2022-07-16 15:47
Just for adding that if I play the same movie from the Disney+ addon directly (without using Timers) it works

**Comment by Heckie75** [comment] 2022-07-16 19:25
@bttfba 
I'm in vacation for another week. Then I can take a look at it.

The problem is that the addon tries to determine the media type such as Video, audio etc.

Please provide the settings.xml file at least the entries that belong to the specific timer. Is there a setting key for media type?

**Comment by Heckie75** [comment] 2022-07-16 19:28
@bttfba 

If you dare you can try the latest version that is in development but stable. See https://github.com/Heckie75/kodi-addon-timers/tree/script.timers.3.3.0

Backup your settings since it is a total new version with totally different settings.

**Comment by bttfba** [comment] 2022-07-16 21:15
Adding here the setting files: used movie "Alladin" timed with Timer_10 for the 23:00
Saved the setting before expiration and after expiration (failed anyway)
[settings - Copy before start.zip](https://github.com/Heckie75/kodi-addon-timers/files/9126602/settings.-.Copy.before.start.zip)
[settings - Copy after start failed.zip](https://github.com/Heckie75/kodi-addon-timers/files/9126604/settings.-.Copy.after.start.failed.zip)

**Comment by bttfba** [comment] 2022-07-16 21:32
Installed the new version (3.3.0) but I don't know how to set the timer anymore: going to the movie, right click on it, I see the menu but "TIMERS" is no there anymore
On the other hand, I can go to "TIMERS" addon, open it, add a timer (or edit it), but no way to link it with the movie I need to play ...
a bit lost ... should I update something else?

**Comment by Heckie75** [comment] 2022-07-17 05:58
@bttfba 
Strange, may be you must restart Kodi. Is the menu missing for all resources or only on specific ones.

**Comment by Heckie75** [comment] 2022-07-17 06:52
@bttfba 

A problem of the Disney addon ist that it does not seem to follow the Rules, since the path ist

plugin://slyguy.disney.plus/?_=play&amp;_play=1&amp;content_id=c9fd8fa3-fa17-4456-9b37-a5427e308f0e&amp;profile_id=eb3428cc-ce10-4b49-af5a-fc666f1a6666

But it should start like 

plugin://video.disney.plus/?...

However, i will take a look at it after my vacation.

Of course I'm interested in your issues releated to Version 3.3.0

**Comment by bttfba** [comment] 2022-07-17 09:36
Ok, now i see the "add timer" menu when right clicking on a media. Sorry for that, maybe my fault, even if I restarted Kodi ... today I restarted the PC ... maybe a deeper alignment.
Unfortunately, Disney+ doesn't work, as before. Log is the same (attached anyway)
Not sure if there is a "setting.xml" file to save, as before. In case let me know
Anyway, enjoy your holidays, will talk when you're back
Ciao!
Fabio
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/9127351/kodi.log)

**Comment by bttfba** [comment] 2022-07-17 13:37
@Heckie75 
Just an additional info: loaded the old version 2.2.0 (maybe same as 3.0.0) and it works
In that version, there is a function:

def build_playlist_from_urls(urls, type=_VIDEO) -> xbmc.PlayList:

    _type_id = _TYPES.index(type)
    playlist = xbmc.PlayList(_type_id)
    playlist.clear()

    for u in urls:
        playlist.add(u)

    return playlist

this probably was doing something in addition to the one now in the lib
Anyway, up to you, I just wanted to verify that from Disney and Slyguy side there are no changes impacting the addon
Fabio

**Comment by Heckie75** [comment] 2022-07-18 06:02
@bttfba 

There is propably a fallback required in case that the media type can not be determined. In script.timers\resources\lib\utils\vfs_utils.py you can change line 216 Like this:

_type_id = TYPES.index(type or VIDEO)

You need to restart Kodi so that changes take effect.

**Comment by bttfba** [comment] 2022-07-18 11:07
Done and working!
That's great
Thank Heckie!

Fabio

Il lun 18 lug 2022, 08:02 Heckie ***@***.***> ha scritto:

**Comment by Heckie75** [comment] 2022-07-23 10:15
@bttfba 
This should be fixed in 3.3.0-pre2, see https://github.com/Heckie75/kodi-addon-timers/tree/script.timers.3.3.0

**Comment by bttfba** [comment] 2022-08-06 21:20
@Heckie75 
i tested the issue on 3.2.0-pre7 and it works, so i think you could close this issue.
the new implementation is great, now i can set all the timers i need (16, actually), so i thank you for all the work done
Thank you
Fabio

**Closed** 2022-08-07 11:04 UTC
