### ISSUE TITLE
New feature: allow Timers for playlist, too

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#7] opened 2022-03-09 09:16 UTC
If I'm not wrong, Timers is not allowed for playlists.
It would be great to have the possibility to play a whole playlist at a fixed time 
Thanks

**Comment by Heckie75** [comment] 2022-03-10 12:21
I am going to check why it isn't possible and what is to do. Acually playlists are totally new for me. 

Are there only available in music section?

I would tyy to do the following if possible:
* allow to select playlists from context menu and do all the intern stuff required to play playlists
* allow to select folders and internally convert contents to playlists

**Comment by Heckie75** [comment] 2022-03-10 12:35
Difficulty: medium
Estimation: approw. 0,5 days

**Comment by bttfba** [comment] 2022-03-10 19:57
Heckie75, thanks a lot for your answers.
It would be absolutely great to have this done, especially for folders: setting a timer for a whole folder would be even better than doing it for a playlist, which is actually a bit tricky in its creating and working.
Of course i fully understand your time problems, so, when you can, it is always fine. But please, consider this improvement as the most important, so, if you only have half a day available, please spend it for this new feature.
My most sincere thanks for your help

**Comment by Heckie75** [comment] 2022-03-12 06:17
@bttfba 

I have implemented the suppor of playlists / folders.

Take a look at this version: https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre1.zip

You can download it and install it as zip archive. Note that this is some kind of beta and not tested very well yet.

**Comment by bttfba** [comment] 2022-03-12 10:25
Hi Heckie75,
thanks for the job done!
unfortunately, it worked only once, then now i'm having this error (sorry,
it is italian, but saying see the logger for details).
Logger attached

Look at 11:00:00 - starting the first video file, duration 1 min 48 seconds
after that it returned (stop playing) even if there are more files in the
same folder; following tries to start timers failed with same error windows.
Last one at 11:06:00

I see I have version 19.3 of Kodi, better to go to 19.4 ?

Thanks
Fabio

[image: image.png]




Il giorno sab 12 mar 2022 alle ore 07:17 Heckie ***@***.***>
ha scritto:

**Comment by Heckie75** [comment] 2022-03-12 12:02
@bttfba 

I didn't some changes. pls. try this one: https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre2.zip

**Comment by bttfba** [comment] 2022-03-12 14:08
@Heckie75 
Still some issues ... same little window saying: play failed on one or many files - see logger
Nothing playing
I attach the log file - timer 1 set for 15:05

![image](https://user-images.githubusercontent.com/63963354/158021124-4b33f63c-52a5-424b-af43-94d59509f0de.png)
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/8237728/kodi.log)
thanks
Fabio

**Comment by Heckie75** [comment] 2022-03-12 14:20
@bttfba 
According the log files there are other files than music and video in the directory, e.g. *.sub or *.peb files. 

Of course, these files are not playable. Playing directories work in general, but since I just add all files this probably happens. May be it is possible to filter so that there are only playable files but I am not sure if the Kodi API is able to determine whatˋs playable and what is not. If not I have to implemt a filter myself, i.e. by suffix of filename, e.g. *.mov, *.mp4, *.mp3

**Comment by bttfba** [comment] 2022-03-12 14:33
That's right, few support files disturbing ...
retried after removing the non-video files and it is absolutely great! Working fine, at least at a first look.

Give me a couple of days of more deep test and then i can close the issue
So you have been really kind and fast! Thank you so much

I'll be back in couple of days
Thanks again!
Fabio

**Comment by Heckie75** [comment] 2022-03-12 17:03
@bttfba 
I have added a filter.

Pls. check https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre3.zip

**Comment by bttfba** [comment] 2022-03-12 22:18
@Heckie75 
the filter works: tried with some non-video files and they are correctly skipped and no error on playing the others.

After this, i tried with a Playlist: got an error (usual little window) - Log attached: Playlist timer started at time 22:53:00
Apparently, a "/" is missing in the file name (name of the playlist is "PL_Cuba.m3u")
Thanks
Fabio
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/8238573/kodi.log)

**Comment by Heckie75** [comment] 2022-03-13 12:38
@bttfba 

Pls. check the updated version https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre4.zip

**Comment by bttfba** [comment] 2022-03-13 15:24
@Heckie75 
I'm sorry, i got an error just after loading the new version from zip file: Timers Error - see log for m ore details
Attached the last log
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/8239945/kodi.log)

**Comment by Heckie75** [comment] 2022-03-13 18:24
@bttfba 
Ok, I was struggeling the whole day with the seeking of playlists. However, there is a wrong "import".

here is a new version: https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre5.zip

**Comment by Heckie75** [comment] 2022-03-14 10:48
@bttfba 

The problem is again the missing slash (special://profile/playlists/video/PL_Cuba.m3uCuba 2017-18 002.MOV) but I can't reproduce this error at least if I set up a timer by using the latest version. Have you set up a new timer or was it a timer that you have setup with an earlier version?

**Comment by bttfba** [comment] 2022-03-14 14:23
@Heckie75 
I did it once more from scratch: reloaded 'pre5' from zip, created a new PL (not easy to do, actually), used a new timer (#8), same problem of the missing "/"
Attached the log
[kodi.log](https://github.com/Heckie75/kodi-addon-timers/files/8245638/kodi.log)

**Comment by Heckie75** [comment] 2022-03-14 17:21
@bttfba 

Ok, I found the bug. Pls. check this one: https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.2.2.0-pre7.zip

**Comment by bttfba** [comment] 2022-03-14 22:49
@Heckie75 
I did some additional tests: 
  - playlists with videos and with music
  - folders with videos and with music
  - several kind of stops (time, duration, no actions)
I didn't find any issue, so for me it works

I wait for your opinion, then i think i can close the issue.
Again, i want to thank you so much, you have been really fast and precise, great job!
Ciao
Fabio

**Comment by Heckie75** [comment] 2022-03-15 08:13
@bttfba 

Keep in mind that I won't merge my changes into official repository before I have finished all changes. I'm going to work also on #8 and #9. It is already prepared but I want to refactor the seetings. That's why it would probably take some more weeks until everything is available in the official repo. You can use the pre-release., of course.

Thanks for testing. I'm going to close this issue. 

BWT: The most tricky was to implement that the playlist will seek to the correct title / position in case that the timer starts late, i.e. since Kodi was not running when timer should have been started.

**Closed by Heckie75** 2022-03-15 08:13 UTC
