### ISSUE TITLE
The repeat flag in Timer Addon doesn't work

### ISSUE THREAD

**Issue by bttfba** [Heckie75/kodi-addon-timers#39] opened 2024-07-12 16:49 UTC
Hi Heckie75
It seems that the "Repeat" flag when setting a timer (on a directory containing several video files) doesn't work anymore. At the end of playing the last file, the player goes idle, not playing anything more.
I'm running KODI 21.0 (21.0.0) and TIMER version 3.9.1
Thanks
Fabio

**Comment by Heckie75** [comment] 2024-07-12 18:38
I have tested it with Kodi 20.x and haven't seen any issues. I'm going to test it with Kodi 21 the next days. 

You can check if the repeat symbol of the player is activated since this is the only thing that the Timer addon does. The addon is not responsible to control repetitions. 

![grafik](https://github.com/user-attachments/assets/1e3dc371-1f07-4ab3-b5e6-3042bd46cd1d)

**Comment by bttfba** [comment] 2024-07-12 22:04
[image: image.png]

[image: image.png]

As you can see, there is no "repeat" flag set during playout of the file.
The point is that I set the timer on the directory, not on the single file.
So, all files in the DIR are played, one after the other, but at the end
the player stops.

If I open the Playlist symbol, the "repeat" is actually deactivated.
[image: image.png]
Clicking on "Repeat" (in the left menu), first shown value is "all", as it
probably should be when i set the "repeat" flag in the timer setup.

Just to help you understand what is happening
Thanks
Ciao
Fabio


Il giorno ven 12 lug 2024 alle ore 20:38 Heckie ***@***.***>
ha scritto:

**Comment by Heckie75** [comment] 2024-07-13 17:24
@bttfba I have also tested with Kode v21.0 under WIndows but can't reproduce this behavior. For me it still works. Your screenhots don't show the player settings that I mean. Maybe press tab key until you see the player view. The player controls appear after you have moved the mouse.

**Comment by bttfba** [comment] 2024-07-13 22:39
ya, my screen shots were wrong ...
![image](https://github.com/user-attachments/assets/5e83b293-9232-4535-b9f7-1d3a785854be)

You see there is no "loop" flag set.

But are you testing with a single file or with a playlist/directory?

**Comment by Heckie75** [comment] 2024-07-14 04:15
@bttfba I have tested with a playlist where the media type was audio / audio player.

As you can see in your screenshot you are testing with video / video player. It seems that repeat functionality is not given for video at all. But this isn't related to the addon. That's how Kodi works.

What I can do is that repeat functionality is not provided if media type is video.

**Comment by Heckie75** [comment] 2024-07-16 19:14
@bttfba Can you confirm that it is related to video? Can this ticket be closed?

**Comment by bttfba** [comment] 2024-07-16 20:54
Yes, I saw the problem trying to repeat a directory with video files
Not sure the ticket can be closed: before the repeat worked, now it doesn't
work anymore.
If the problem is related to different sw area, please let me know and you
can close this ticket
Thanks


Il mar 16 lug 2024, 21:14 Heckie ***@***.***> ha scritto:

**Comment by Heckie75** [comment] 2024-07-17 05:56
@bttfba As mentioned I can't see that it has worked differently before. I have tested directories with video files in Kodi 20.x as well and have seen the same situation as in Kodi 21.0. Maybe you can try to set the media type to audio in timer settings (I think expert setttings) or mix the directory so that there are also audio files in there. 

The timer add-on does not control that media is repeated. It just sets the player option to repeat. 

I'm going to close this ticket since there is nothing I can do.

**Closed by Heckie75** 2024-07-17 05:56 UTC

**Comment by Heckie75** [comment] 2024-07-17 06:10
After a few more minutes of investigation you can do the following:
1. add the files of your folder in a playlist
2. save this playlist
3. The playlist is displayed in the playlist section
4. add playlist to timer

then it works

**Comment by Heckie75** [comment] 2024-07-21 07:06
@bttfba  I have probably found a solution. May be take a look at version 3.9.2, see https://github.com/Heckie75/kodi-addon-timers/raw/master/script.timers.3.9.2.zip

**Comment by bttfba** [comment] 2024-07-26 16:43
i actually don't see real improvements with 3.9.2 ...

**Comment by Heckie75** [comment] 2024-07-27 09:04
@bttfba Have you restarted Kodi after updating the addon?

**Comment by bttfba** [comment] 2024-07-27 09:23
Yes, I did.

Il sab 27 lug 2024, 11:04 Heckie ***@***.***> ha scritto:

**Comment by Heckie75** [comment] 2024-07-27 14:50
@bttfba Sorry, I can't reproduce this problem. I have tested the latest version of the addon on Linux (Kodi v20.2) and Windows (Kodi v21.0).
